version: "3.9"
services:
  nextjs:
    image: jonathanleedev/sparrow-ui-nextjs:latest
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: jonathanleedev/sparrow-ui-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SERVER_CERT_PATH}:/etc/nginx/server.crt
      - ${SERVER_KEY_PATH}:/etc/nginx/server.key
    restart: always
